WITH tags AS (
    SELECT id, code FROM t_tag
),
drill_tag_pairs (db_name, tag_code) AS (
    VALUES
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Pull-Up', '15FT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Pull-Up', 'CURL_CUT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Pull-Up', 'FADE_CUT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Pull-Up', 'FL_TOP_OF_FT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Pull-Up', 'PULL_UP_L'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Pull-Up', 'REGULAR'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Step-Back', '15FT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Step-Back', 'CURL_CUT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Step-Back', 'FADE_CUT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Step-Back', 'FL_TOP_OF_FT'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Step-Back', 'REGULAR'),
        ('15 ft No-Ball Movement Series – Curl → Fade → Left Step-Back', 'STEP_BACK_L'),
        ('15 ft Shot → 3-Point Shot (Back and Forth)', '15FT'),
        ('15 ft Shot → 3-Point Shot (Back and Forth)', '3PT'),
        ('15 ft Shot → 3-Point Shot (Back and Forth)', 'DEPTH_SHOOTING'),
        ('15 ft Shot → 3-Point Shot (Back and Forth)', 'REGULAR'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Left Hand)', '15FT'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Left Hand)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Left Hand)', 'BEHIND_THE_BACK'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Left Hand)', 'FL_L_ELBOW'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Left Hand)', 'PULL_UP_L'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Left Hand)', 'REGULAR'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Right Hand)', '15FT'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Right Hand)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Right Hand)', 'BEHIND_THE_BACK'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Right Hand)', 'FL_R_ELBOW'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Right Hand)', 'PULL_UP_R'),
        ('15 ft – 2-Dribble Behind-the-Back (Start Right Hand)', 'REGULAR'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', '15FT'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', 'BETWEEN_THE_LEGS'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', 'COMBO_MOVE'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', 'FL_L_ELBOW'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', 'PULL_UP_L'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Left Hand)', 'REGULAR'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', '15FT'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', 'BETWEEN_THE_LEGS'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', 'COMBO_MOVE'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', 'FL_R_ELBOW'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', 'PULL_UP_R'),
        ('15 ft – 2-Dribble Between-the-Legs (Start Right Hand)', 'REGULAR'),
        ('15 ft – 2-Dribble Inside-Out (Left)', '15FT'),
        ('15 ft – 2-Dribble Inside-Out (Left)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Inside-Out (Left)', 'FL_TOP_OF_FT'),
        ('15 ft – 2-Dribble Inside-Out (Left)', 'IN_AND_OUT'),
        ('15 ft – 2-Dribble Inside-Out (Left)', 'PULL_UP_L'),
        ('15 ft – 2-Dribble Inside-Out (Left)', 'REGULAR'),
        ('15 ft – 2-Dribble Inside-Out (Right)', '15FT'),
        ('15 ft – 2-Dribble Inside-Out (Right)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Inside-Out (Right)', 'FL_TOP_OF_FT'),
        ('15 ft – 2-Dribble Inside-Out (Right)', 'IN_AND_OUT'),
        ('15 ft – 2-Dribble Inside-Out (Right)', 'PULL_UP_R'),
        ('15 ft – 2-Dribble Inside-Out (Right)', 'REGULAR'),
        ('15 ft – 2-Dribble Pull-Up (Left → Front Crossover)', '15FT'),
        ('15 ft – 2-Dribble Pull-Up (Left → Front Crossover)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Pull-Up (Left → Front Crossover)', 'FL_L_ELBOW'),
        ('15 ft – 2-Dribble Pull-Up (Left → Front Crossover)', 'FRONT_CROSS'),
        ('15 ft – 2-Dribble Pull-Up (Left → Front Crossover)', 'PULL_UP_L'),
        ('15 ft – 2-Dribble Pull-Up (Left → Front Crossover)', 'REGULAR'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', '15FT'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', '2_DRIBBLE'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', 'COMBO_MOVE'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', 'FL_R_ELBOW'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', 'FL_TOP_OF_FT'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', 'FRONT_CROSS'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', 'PULL_UP_R'),
        ('15 ft – 2-Dribble Pull-Up (Right → Front Crossover)', 'REGULAR'),
        ('15 ft – Catch & Shoot / Self-Spin', '15FT'),
        ('15 ft – Catch & Shoot / Self-Spin', 'CATCH_AND_SHOOT'),
        ('15 ft – Catch & Shoot / Self-Spin', 'FL_TOP_OF_FT'),
        ('15 ft – Catch & Shoot / Self-Spin', 'REGULAR'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Re-Shoot', '15FT'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Re-Shoot', 'CURL_CUT'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Re-Shoot', 'FL_L_ELBOW'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Re-Shoot', 'REGULAR'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Re-Shoot', 'RESHOOT'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Re-Shoot', 'SHOT_FAKE'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Step-Back', '15FT'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Step-Back', 'CURL_CUT'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Step-Back', 'FL_L_ELBOW'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Step-Back', 'REGULAR'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Step-Back', 'SHOT_FAKE'),
        ('15 ft – Cut to Left Elbow → Shot Fake → Step-Back', 'STEP_BACK_L'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Re-Shoot', '15FT'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Re-Shoot', 'CURL_CUT'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Re-Shoot', 'FL_R_ELBOW'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Re-Shoot', 'REGULAR'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Re-Shoot', 'RESHOOT'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Re-Shoot', 'SHOT_FAKE'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Step-Back', '15FT'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Step-Back', 'CURL_CUT'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Step-Back', 'FL_R_ELBOW'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Step-Back', 'REGULAR'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Step-Back', 'SHOT_FAKE'),
        ('15 ft – Cut to Right Elbow → Shot Fake → Step-Back', 'STEP_BACK_R'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Left Hand)', '15FT'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Left Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Left Hand)', 'HESITATE'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Left Hand)', 'JAB'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Left Hand)', 'PULL_UP_L'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Left Hand)', 'REGULAR'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Right Hand)', '15FT'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Right Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Right Hand)', 'HESITATE'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Right Hand)', 'JAB'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Right Hand)', 'PULL_UP_R'),
        ('15 ft – Jab → Relax → Tempo Change → Pull-Up (Right Hand)', 'REGULAR'),
        ('15 ft – One-Dribble Pull-Up (Left)', '15FT'),
        ('15 ft – One-Dribble Pull-Up (Left)', '1_DRIBBLE'),
        ('15 ft – One-Dribble Pull-Up (Left)', 'FL_TOP_OF_FT'),
        ('15 ft – One-Dribble Pull-Up (Left)', 'PULL_UP_L'),
        ('15 ft – One-Dribble Pull-Up (Left)', 'REGULAR'),
        ('15 ft – One-Dribble Pull-Up (Right)', '15FT'),
        ('15 ft – One-Dribble Pull-Up (Right)', '1_DRIBBLE'),
        ('15 ft – One-Dribble Pull-Up (Right)', 'FL_TOP_OF_FT'),
        ('15 ft – One-Dribble Pull-Up (Right)', 'PULL_UP_R'),
        ('15 ft – One-Dribble Pull-Up (Right)', 'REGULAR'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Left)', '15FT'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Left)', '1_DRIBBLE'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Left)', 'FL_TOP_OF_FT'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Left)', 'PULL_UP_L'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Left)', 'REGULAR'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Left)', 'STEP_BACK_L'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Right)', '15FT'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Right)', '1_DRIBBLE'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Right)', 'FL_TOP_OF_FT'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Right)', 'PULL_UP_R'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Right)', 'REGULAR'),
        ('15 ft – One-Dribble Step-Back Pull-Up (Right)', 'STEP_BACK_R'),
        ('15 ft – Shot Fake → Left-Hand Slide Dribble', '15FT'),
        ('15 ft – Shot Fake → Left-Hand Slide Dribble', '1_DRIBBLE'),
        ('15 ft – Shot Fake → Left-Hand Slide Dribble', 'FL_L_ELBOW'),
        ('15 ft – Shot Fake → Left-Hand Slide Dribble', 'REGULAR'),
        ('15 ft – Shot Fake → Left-Hand Slide Dribble', 'SHOT_FAKE'),
        ('15 ft – Shot Fake → Left-Hand Slide Dribble', 'SLIDE_DRIBBLE_L'),
        ('15 ft – Shot Fake → Right-Hand Slide Dribble', '15FT'),
        ('15 ft – Shot Fake → Right-Hand Slide Dribble', '1_DRIBBLE'),
        ('15 ft – Shot Fake → Right-Hand Slide Dribble', 'FL_R_ELBOW'),
        ('15 ft – Shot Fake → Right-Hand Slide Dribble', 'REGULAR'),
        ('15 ft – Shot Fake → Right-Hand Slide Dribble', 'SHOT_FAKE'),
        ('15 ft – Shot Fake → Right-Hand Slide Dribble', 'SLIDE_DRIBBLE_R'),
        ('15 ft – Slide Dribble (Left Hand)', '15FT'),
        ('15 ft – Slide Dribble (Left Hand)', '1_DRIBBLE'),
        ('15 ft – Slide Dribble (Left Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – Slide Dribble (Left Hand)', 'REGULAR'),
        ('15 ft – Slide Dribble (Left Hand)', 'SLIDE_DRIBBLE_L'),
        ('15 ft – Slide Dribble (Right Hand)', '15FT'),
        ('15 ft – Slide Dribble (Right Hand)', '1_DRIBBLE'),
        ('15 ft – Slide Dribble (Right Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – Slide Dribble (Right Hand)', 'REGULAR'),
        ('15 ft – Slide Dribble (Right Hand)', 'SLIDE_DRIBBLE_R'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', '15FT'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', '2_DRIBBLE'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', 'FAST_BREAK'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', 'FL_TOP_OF_FT'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', 'PULL_UP_L'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', 'REGULAR'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Left)', 'TRANSITION'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', '15FT'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', '2_DRIBBLE'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', 'FAST_BREAK'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', 'FL_TOP_OF_FT'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', 'PULL_UP_R'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', 'REGULAR'),
        ('15 ft – Sprint 2-Dribble Pull-Up (Right) (FB 3pt)', 'TRANSITION'),
        ('15 ft – Through Legs → Behind Back (Left Hand)', '15FT'),
        ('15 ft – Through Legs → Behind Back (Left Hand)', 'BEHIND_THE_BACK'),
        ('15 ft – Through Legs → Behind Back (Left Hand)', 'BETWEEN_THE_LEGS'),
        ('15 ft – Through Legs → Behind Back (Left Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – Through Legs → Behind Back (Left Hand)', 'PULL_UP_L'),
        ('15 ft – Through Legs → Behind Back (Left Hand)', 'REGULAR'),
        ('15 ft – Through Legs → Behind Back (Right Hand)', '15FT'),
        ('15 ft – Through Legs → Behind Back (Right Hand)', 'BEHIND_THE_BACK'),
        ('15 ft – Through Legs → Behind Back (Right Hand)', 'BETWEEN_THE_LEGS'),
        ('15 ft – Through Legs → Behind Back (Right Hand)', 'FL_TOP_OF_FT'),
        ('15 ft – Through Legs → Behind Back (Right Hand)', 'PULL_UP_R'),
        ('15 ft – Through Legs → Behind Back (Right Hand)', 'REGULAR'),
        ('15 ft – Two‑Dribble Shot fake Pull-Up (Right)', '15FT'),
        ('15 ft – Two‑Dribble Shot fake Pull-Up (Right)', '2_DRIBBLE'),
        ('15 ft – Two‑Dribble Shot fake Pull-Up (Right)', 'FL_TOP_OF_FT'),
        ('15 ft – Two‑Dribble Shot fake Pull-Up (Right)', 'PULL_UP_R'),
        ('15 ft – Two‑Dribble Shot fake Pull-Up (Right)', 'REGULAR'),
        ('15 ft – Two‑Dribble Shot fake Pull-Up (Right)', 'SHOT_FAKE'),
        ('3-Point Distance – Two Spots, Back-to-Basket Start', '3PT'),
        ('3-Point Distance – Two Spots, Back-to-Basket Start', 'DEPTH_SHOOTING'),
        ('3-Point Distance – Two Spots, Back-to-Basket Start', 'FL_TOP_OF_KEY_3PT'),
        ('3-Point Distance – Two Spots, Back-to-Basket Start', 'REGULAR'),
        ('3-Point Fade Cut → Corner 3', '3PT'),
        ('3-Point Fade Cut → Corner 3', 'FADE_CUT'),
        ('3-Point Fade Cut → Corner 3', 'FL_3PT_WING_R'),
        ('3-Point Fade Cut → Corner 3', 'FL_CORNER_3_R'),
        ('3-Point Fade Cut → Corner 3', 'REGULAR'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', '15FT'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', '2_DRIBBLE'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', '3PT'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'DEPTH_SHOOTING'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'FRONT_CROSS'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'IN_AND_OUT'),
        ('3-Point Left → 15 ft Left (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'REGULAR'),
        ('3-Point Right → 15 ft Right (1-Dribble Back & Forth)', '15FT'),
        ('3-Point Right → 15 ft Right (1-Dribble Back & Forth)', '1_DRIBBLE'),
        ('3-Point Right → 15 ft Right (1-Dribble Back & Forth)', '3PT'),
        ('3-Point Right → 15 ft Right (1-Dribble Back & Forth)', 'DEPTH_SHOOTING'),
        ('3-Point Right → 15 ft Right (1-Dribble Back & Forth)', 'REGULAR'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', '15FT'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', '2_DRIBBLE'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', '3PT'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'DEPTH_SHOOTING'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'FRONT_CROSS'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'IN_AND_OUT'),
        ('3-Point Right → 15 ft Right (2-Dribble In-and-Out → Front Crossover → Back & Forth)', 'REGULAR'),
        ('3-Point – Catch & Shoot / Self-Spin', '3PT'),
        ('3-Point – Catch & Shoot / Self-Spin', 'CATCH_AND_SHOOT'),
        ('3-Point – Catch & Shoot / Self-Spin', 'FL_TOP_OF_KEY_3PT'),
        ('3-Point – Catch & Shoot / Self-Spin', 'REGULAR'),
        ('3-Point – One-Dribble Pull-Up (Left)', '1_DRIBBLE'),
        ('3-Point – One-Dribble Pull-Up (Left)', '3PT'),
        ('3-Point – One-Dribble Pull-Up (Left)', 'FL_TOP_OF_KEY_3PT'),
        ('3-Point – One-Dribble Pull-Up (Left)', 'PULL_UP_L'),
        ('3-Point – One-Dribble Pull-Up (Left)', 'REGULAR'),
        ('3-Point – One-Dribble Pull-Up (Right)', '1_DRIBBLE'),
        ('3-Point – One-Dribble Pull-Up (Right)', '3PT'),
        ('3-Point – One-Dribble Pull-Up (Right)', 'FL_TOP_OF_KEY_3PT'),
        ('3-Point – One-Dribble Pull-Up (Right)', 'PULL_UP_R'),
        ('3-Point – One-Dribble Pull-Up (Right)', 'REGULAR'),
        ('3-Point – One-Dribble Slide Dribble (Left)', '1_DRIBBLE'),
        ('3-Point – One-Dribble Slide Dribble (Left)', '3PT'),
        ('3-Point – One-Dribble Slide Dribble (Left)', 'FL_TOP_OF_KEY_3PT'),
        ('3-Point – One-Dribble Slide Dribble (Left)', 'REGULAR'),
        ('3-Point – One-Dribble Slide Dribble (Left)', 'SLIDE_DRIBBLE_L'),
        ('3-Point – One-Dribble Slide Dribble (Right)', '1_DRIBBLE'),
        ('3-Point – One-Dribble Slide Dribble (Right)', '3PT'),
        ('3-Point – One-Dribble Slide Dribble (Right)', 'FL_TOP_OF_KEY_3PT'),
        ('3-Point – One-Dribble Slide Dribble (Right)', 'REGULAR'),
        ('3-Point – One-Dribble Slide Dribble (Right)', 'SLIDE_DRIBBLE_R'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', '3PT'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'CHAIR'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'CURL_CUT'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'REGULAR'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'RESHOOT'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'RIP'),
        ('3‑Point Chair Inside Curl → Rip → Fake → Reshape Shot', 'SHOT_FAKE'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', '3PT'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', 'CHAIR'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', 'DOUBLE_JAB'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', 'FACE_CUT'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', 'PULL_UP_R'),
        ('3‑Point Chair Series – Fake, Face Cut, Return Pull-Up', 'REGULAR'),
        ('3‑Point – Slide Dribble Right → Double Move Left', '3PT'),
        ('3‑Point – Slide Dribble Right → Double Move Left', 'COMBO_MOVE'),
        ('3‑Point – Slide Dribble Right → Double Move Left', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Slide Dribble Right → Double Move Left', 'PULL_UP_L'),
        ('3‑Point – Slide Dribble Right → Double Move Left', 'REGULAR'),
        ('3‑Point – Slide Dribble Right → Double Move Left', 'SLIDE_DRIBBLE_R'),
        ('3‑Point – Slide Dribble Right → Double Move Right', '3PT'),
        ('3‑Point – Slide Dribble Right → Double Move Right', 'COMBO_MOVE'),
        ('3‑Point – Slide Dribble Right → Double Move Right', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Slide Dribble Right → Double Move Right', 'PULL_UP_R'),
        ('3‑Point – Slide Dribble Right → Double Move Right', 'REGULAR'),
        ('3‑Point – Slide Dribble Right → Double Move Right', 'SLIDE_DRIBBLE_R'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Left', '3PT'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Left', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Left', 'REGULAR'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Left', 'SHOT_FAKE'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Left', 'SLIDE_DRIBBLE_L'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Left', 'TRANSITION'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Right', '3PT'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Right', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Right', 'REGULAR'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Right', 'SHOT_FAKE'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Right', 'SLIDE_DRIBBLE_R'),
        ('3‑Point – Transition 3 → Shot Fake → Slide Right', 'TRANSITION'),
        ('3‑Point – Transition 3s', '3PT'),
        ('3‑Point – Transition 3s', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Transition 3s', 'REGULAR'),
        ('3‑Point – Transition 3s', 'TRANSITION'),
        ('3‑Point – Two Cones (Inside Pivot → Swing Step)', '3PT'),
        ('3‑Point – Two Cones (Inside Pivot → Swing Step)', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Two Cones (Inside Pivot → Swing Step)', 'INSIDE_PIVOT'),
        ('3‑Point – Two Cones (Inside Pivot → Swing Step)', 'REGULAR'),
        ('3‑Point – Two Cones (Inside Pivot → Swing Step)', 'SWING_STEP'),
        ('3‑Point – Two Spot Movement (5 ft Apart)', '3PT'),
        ('3‑Point – Two Spot Movement (5 ft Apart)', 'DEPTH_SHOOTING'),
        ('3‑Point – Two Spot Movement (5 ft Apart)', 'FL_TOP_OF_KEY_3PT'),
        ('3‑Point – Two Spot Movement (5 ft Apart)', 'REGULAR'),
        ('Attack → Pause → Behind-Back Retreat → 3', '3PT'),
        ('Attack → Pause → Behind-Back Retreat → 3', 'BEHIND_THE_BACK'),
        ('Attack → Pause → Behind-Back Retreat → 3', 'FL_R_ELBOW'),
        ('Attack → Pause → Behind-Back Retreat → 3', 'FL_TOP_OF_KEY_3PT'),
        ('Attack → Pause → Behind-Back Retreat → 3', 'REGULAR'),
        ('Attack → Pause → Behind-Back Retreat → 3', 'RETREAT_DRIBBLE'),
        ('Attack → Pause → Behind-Back Retreat → 3 (Other Side)', '3PT'),
        ('Attack → Pause → Behind-Back Retreat → 3 (Other Side)', 'BEHIND_THE_BACK'),
        ('Attack → Pause → Behind-Back Retreat → 3 (Other Side)', 'FL_L_ELBOW'),
        ('Attack → Pause → Behind-Back Retreat → 3 (Other Side)', 'FL_TOP_OF_KEY_3PT'),
        ('Attack → Pause → Behind-Back Retreat → 3 (Other Side)', 'REGULAR'),
        ('Attack → Pause → Behind-Back Retreat → 3 (Other Side)', 'RETREAT_DRIBBLE'),
        ('Attack → Under-Drag → Step-Back 3', '3PT'),
        ('Attack → Under-Drag → Step-Back 3', 'FL_TOP_OF_KEY_3PT'),
        ('Attack → Under-Drag → Step-Back 3', 'REGULAR'),
        ('Attack → Under-Drag → Step-Back 3', 'STEP_BACK_R'),
        ('Attack → Under-Drag → Step-Back 3', 'UNDER_DRAG'),
        ('Attack → Under-Drag → Step-Back 3 (Other Side)', '3PT'),
        ('Attack → Under-Drag → Step-Back 3 (Other Side)', 'FL_TOP_OF_KEY_3PT'),
        ('Attack → Under-Drag → Step-Back 3 (Other Side)', 'REGULAR'),
        ('Attack → Under-Drag → Step-Back 3 (Other Side)', 'STEP_BACK_L'),
        ('Attack → Under-Drag → Step-Back 3 (Other Side)', 'UNDER_DRAG'),
        ('Back Screen Pop-Out (Left) – Attack Middle → 2-Dribble Turnaround', '15FT'),
        ('Back Screen Pop-Out (Left) – Attack Middle → 2-Dribble Turnaround', '2_DRIBBLE'),
        ('Back Screen Pop-Out (Left) – Attack Middle → 2-Dribble Turnaround', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Left) – Attack Middle → 2-Dribble Turnaround', 'FL_L_ELBOW'),
        ('Back Screen Pop-Out (Left) – Attack Middle → 2-Dribble Turnaround', 'REGULAR'),
        ('Back Screen Pop-Out (Left) – Attack Middle → 2-Dribble Turnaround', 'TURNAROUND'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Fake Drop-Step Spin → Turnaround', '15FT'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'FAKE_DROP_STEP'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'FL_L_ELBOW'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'REGULAR'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'TURNAROUND'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', '15FT'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', 'FL_L_ELBOW'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', 'REGULAR'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', 'RESHOOT'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', 'SHOT_FAKE'),
        ('Back Screen Pop-Out (Left) – Attack Middle → Shot Fake → Reshape → Turnaround', 'TURNAROUND'),
        ('Back Screen Pop-Out (Left) – Catch & Shoot', '15FT'),
        ('Back Screen Pop-Out (Left) – Catch & Shoot', 'CATCH_AND_SHOOT'),
        ('Back Screen Pop-Out (Left) – Catch & Shoot', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Left) – Catch & Shoot', 'FL_L_ELBOW'),
        ('Back Screen Pop-Out (Left) – Catch & Shoot', 'REGULAR'),
        ('Back Screen Pop-Out (Right) – Attack Middle → 2-Dribble Turnaround', '15FT'),
        ('Back Screen Pop-Out (Right) – Attack Middle → 2-Dribble Turnaround', '2_DRIBBLE'),
        ('Back Screen Pop-Out (Right) – Attack Middle → 2-Dribble Turnaround', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Right) – Attack Middle → 2-Dribble Turnaround', 'FL_R_ELBOW'),
        ('Back Screen Pop-Out (Right) – Attack Middle → 2-Dribble Turnaround', 'REGULAR'),
        ('Back Screen Pop-Out (Right) – Attack Middle → 2-Dribble Turnaround', 'TURNAROUND'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Fake Drop-Step Spin → Turnaround', '15FT'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'FAKE_DROP_STEP'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'FL_R_ELBOW'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'REGULAR'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Fake Drop-Step Spin → Turnaround', 'TURNAROUND'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', '15FT'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', 'FL_R_ELBOW'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', 'REGULAR'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', 'RESHOOT'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', 'SHOT_FAKE'),
        ('Back Screen Pop-Out (Right) – Attack Middle → Shot Fake → Reshape → Turnaround', 'TURNAROUND'),
        ('Back Screen Pop-Out (Right) – Catch & Shoot', '15FT'),
        ('Back Screen Pop-Out (Right) – Catch & Shoot', 'CATCH_AND_SHOOT'),
        ('Back Screen Pop-Out (Right) – Catch & Shoot', 'FLAT_BALL_SCREEN'),
        ('Back Screen Pop-Out (Right) – Catch & Shoot', 'FL_R_ELBOW'),
        ('Back Screen Pop-Out (Right) – Catch & Shoot', 'REGULAR'),
        ('Back-Down Wing Pick & Roll – Left Hand', '15FT'),
        ('Back-Down Wing Pick & Roll – Left Hand', 'BACK_DOWN'),
        ('Back-Down Wing Pick & Roll – Left Hand', 'FL_TOP_OF_FT'),
        ('Back-Down Wing Pick & Roll – Left Hand', 'PICK_AND_ROLL'),
        ('Back-Down Wing Pick & Roll – Left Hand', 'PULL_UP_L'),
        ('Back-Down Wing Pick & Roll – Left Hand', 'REGULAR'),
        ('Back-Down Wing Pick & Roll – Left Hand', 'SL_L_WING'),
        ('Back-Down Wing Pick & Roll – Right Hand', '15FT'),
        ('Back-Down Wing Pick & Roll – Right Hand', 'BACK_DOWN'),
        ('Back-Down Wing Pick & Roll – Right Hand', 'FL_TOP_OF_FT'),
        ('Back-Down Wing Pick & Roll – Right Hand', 'PICK_AND_ROLL'),
        ('Back-Down Wing Pick & Roll – Right Hand', 'PULL_UP_R'),
        ('Back-Down Wing Pick & Roll – Right Hand', 'REGULAR'),
        ('Back-Down Wing Pick & Roll – Right Hand', 'SL_R_WING'),
        ('Baseline Outside Curl → Catch & Shoot 3', '3PT'),
        ('Baseline Outside Curl → Catch & Shoot 3', 'CATCH_AND_SHOOT'),
        ('Baseline Outside Curl → Catch & Shoot 3', 'CURL_CUT'),
        ('Baseline Outside Curl → Catch & Shoot 3', 'FL_TOP_OF_KEY_3PT'),
        ('Baseline Outside Curl → Catch & Shoot 3', 'REGULAR'),
        ('Baseline Outside Curl → Catch & Shoot 3', 'SL_BASELINE_UNDER_HOOP'),
        ('Baseline Outside Curl → Catch & Shoot 3 (Other Side)', '3PT'),
        ('Baseline Outside Curl → Catch & Shoot 3 (Other Side)', 'CATCH_AND_SHOOT'),
        ('Baseline Outside Curl → Catch & Shoot 3 (Other Side)', 'CURL_CUT'),
        ('Baseline Outside Curl → Catch & Shoot 3 (Other Side)', 'FL_L_ELBOW'),
        ('Baseline Outside Curl → Catch & Shoot 3 (Other Side)', 'REGULAR'),
        ('Baseline Outside Curl → Catch & Shoot 3 (Other Side)', 'SL_BASELINE_UNDER_HOOP'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', '15FT'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'CHAIR'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'FL_L_ELBOW'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'PUSH_OUT'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'REGULAR'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'RESHOOT'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'RIP'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Left Side)', 'SHOT_FAKE'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', '15FT'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'CHAIR'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'FL_R_ELBOW'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'PUSH_OUT'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'REGULAR'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'RESHOOT'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'RIP'),
        ('Chair Rip → Push Extend → Shot Fake → Reshape & Shoot (Right Side)', 'SHOT_FAKE'),
        ('Change Distance Cut Shooting (Right Elbow)', '15FT'),
        ('Change Distance Cut Shooting (Right Elbow)', 'CURL_CUT'),
        ('Change Distance Cut Shooting (Right Elbow)', 'DEPTH_SHOOTING'),
        ('Change Distance Cut Shooting (Right Elbow)', 'FL_L_ELBOW'),
        ('Change Distance Cut Shooting (Right Elbow)', 'FL_R_ELBOW'),
        ('Change Distance Cut Shooting (Right Elbow)', 'REGULAR'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', '3PT'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', 'CHAIR'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', 'FL_CORNER_3_L'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', 'FRONT_CROSS'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', 'PULL_UP_L'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', 'REGULAR'),
        ('Corner to Wing Chair Rip → Cross‑Step Pull-Up (Left Hand)', 'SL_L_CORNER'),
        ('Curl Cut → Midrange Shot (Left Elbow)', '15FT'),
        ('Curl Cut → Midrange Shot (Left Elbow)', 'CATCH_AND_SHOOT'),
        ('Curl Cut → Midrange Shot (Left Elbow)', 'CURL_CUT'),
        ('Curl Cut → Midrange Shot (Left Elbow)', 'FL_L_BLOCK'),
        ('Curl Cut → Midrange Shot (Left Elbow)', 'FL_L_ELBOW'),
        ('Curl Cut → Midrange Shot (Left Elbow)', 'REGULAR'),
        ('Curl Cut → Midrange Shot (Right Elbow)', '15FT'),
        ('Curl Cut → Midrange Shot (Right Elbow)', 'CATCH_AND_SHOOT'),
        ('Curl Cut → Midrange Shot (Right Elbow)', 'CURL_CUT'),
        ('Curl Cut → Midrange Shot (Right Elbow)', 'FL_R_BLOCK'),
        ('Curl Cut → Midrange Shot (Right Elbow)', 'FL_R_ELBOW'),
        ('Curl Cut → Midrange Shot (Right Elbow)', 'REGULAR'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', '15FT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', '1_DRIBBLE'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', '3PT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'BETWEEN_THE_LEGS'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'CATCH_AND_SHOOT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'CURL_CUT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'DEPTH_SHOOTING'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'FL_L_ELBOW'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'PULL_UP_R'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'REGULAR'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'RELOCATE'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Left Elbow)', 'RETREAT_DRIBBLE'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Right Elbow)', '15FT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Right Elbow)', 'CATCH_AND_SHOOT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Right Elbow)', 'CURL_CUT'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Right Elbow)', 'FL_R_ELBOW'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Right Elbow)', 'REGULAR'),
        ('Curl Cut → Pass → Relocate → Catch & Shoot (Right Elbow)', 'RELOCATE'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Left Hand)', '15FT'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Left Hand)', '1_DRIBBLE'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Left Hand)', 'CURL_CUT'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Left Hand)', 'FL_TOP_OF_FT'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Left Hand)', 'REGULAR'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Left Hand)', 'STEP_BACK_L'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Right Hand)', '15FT'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Right Hand)', '1_DRIBBLE'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Right Hand)', 'CURL_CUT'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Right Hand)', 'FL_TOP_OF_FT'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Right Hand)', 'REGULAR'),
        ('Curl → Hoop → Return → One-Dribble Step-Back (Right Hand)', 'STEP_BACK_R'),
        ('Deny Screen Left – Bump Screener → Crossover → 15 ft Pull-Up', '15FT'),
        ('Deny Screen Left – Bump Screener → Crossover → 15 ft Pull-Up', 'FL_TOP_OF_FT'),
        ('Deny Screen Left – Bump Screener → Crossover → 15 ft Pull-Up', 'FRONT_CROSS'),
        ('Deny Screen Left – Bump Screener → Crossover → 15 ft Pull-Up', 'PICK_AND_ROLL'),
        ('Deny Screen Left – Bump Screener → Crossover → 15 ft Pull-Up', 'PULL_UP_L'),
        ('Deny Screen Left – Bump Screener → Crossover → 15 ft Pull-Up', 'REGULAR'),
        ('Double Jab → Attack Baseline → Pull-Up', '15FT'),
        ('Double Jab → Attack Baseline → Pull-Up', 'DOUBLE_JAB'),
        ('Double Jab → Attack Baseline → Pull-Up', 'FL_TOP_OF_FT'),
        ('Double Jab → Attack Baseline → Pull-Up', 'PULL_UP_L'),
        ('Double Jab → Attack Baseline → Pull-Up', 'REGULAR'),
        ('Double Jab → Attack Baseline → Pull-Up', 'SL_BASELINE_UNDER_HOOP'),
        ('Double Jab → Attack Middle → Pull-Up', '15FT'),
        ('Double Jab → Attack Middle → Pull-Up', 'DOUBLE_JAB'),
        ('Double Jab → Attack Middle → Pull-Up', 'FL_MIDDLE_OF_KEY'),
        ('Double Jab → Attack Middle → Pull-Up', 'FL_TOP_OF_FT'),
        ('Double Jab → Attack Middle → Pull-Up', 'PULL_UP_R'),
        ('Double Jab → Attack Middle → Pull-Up', 'REGULAR'),
        ('Double Jab → Cross-Step Attack', '15FT'),
        ('Double Jab → Cross-Step Attack', 'CROSS_STEP'),
        ('Double Jab → Cross-Step Attack', 'DOUBLE_JAB'),
        ('Double Jab → Cross-Step Attack', 'FL_TOP_OF_FT'),
        ('Double Jab → Cross-Step Attack', 'REGULAR'),
        ('Double Jab → Lead Step → Step‑Back (Baseline Attack)', '15FT'),
        ('Double Jab → Lead Step → Step‑Back (Baseline Attack)', 'DOUBLE_JAB'),
        ('Double Jab → Lead Step → Step‑Back (Baseline Attack)', 'FL_TOP_OF_FT'),
        ('Double Jab → Lead Step → Step‑Back (Baseline Attack)', 'LEAD_STEP'),
        ('Double Jab → Lead Step → Step‑Back (Baseline Attack)', 'REGULAR'),
        ('Double Jab → Lead Step → Step‑Back (Baseline Attack)', 'STEP_BACK_R'),
        ('Double Jab → Lead Step → Step‑Back (Middle Attack)', '15FT'),
        ('Double Jab → Lead Step → Step‑Back (Middle Attack)', 'DOUBLE_JAB'),
        ('Double Jab → Lead Step → Step‑Back (Middle Attack)', 'FL_TOP_OF_FT'),
        ('Double Jab → Lead Step → Step‑Back (Middle Attack)', 'LEAD_STEP'),
        ('Double Jab → Lead Step → Step‑Back (Middle Attack)', 'REGULAR'),
        ('Double Jab → Lead Step → Step‑Back (Middle Attack)', 'STEP_BACK_L'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Baseline)', '15FT'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Baseline)', 'DOUBLE_JAB'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Baseline)', 'FL_TOP_OF_FT'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Baseline)', 'REGULAR'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Baseline)', 'RESHOOT'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Baseline)', 'SHOT_FAKE'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Middle)', '15FT'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Middle)', 'DOUBLE_JAB'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Middle)', 'FL_TOP_OF_FT'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Middle)', 'REGULAR'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Middle)', 'RESHOOT'),
        ('Double Jab → Shot Fake → Reshape & Shoot (Middle)', 'SHOT_FAKE'),
        ('Edge Line 3pt line → One Dribble → Into Wrap Around Dribble → Pull Up Shot', '1_DRIBBLE'),
        ('Edge Line 3pt line → One Dribble → Into Wrap Around Dribble → Pull Up Shot', '3PT'),
        ('Edge Line 3pt line → One Dribble → Into Wrap Around Dribble → Pull Up Shot', 'FL_TOP_OF_KEY_3PT'),
        ('Edge Line 3pt line → One Dribble → Into Wrap Around Dribble → Pull Up Shot', 'PULL_UP_R'),
        ('Edge Line 3pt line → One Dribble → Into Wrap Around Dribble → Pull Up Shot', 'REGULAR'),
        ('Edge Line 3pt line → One Dribble → Into Wrap Around Dribble → Pull Up Shot', 'WRAP_DRIBBLE'),
        ('Elbow to Elbow Shot Fake → Reshape → Shot', '15FT'),
        ('Elbow to Elbow Shot Fake → Reshape → Shot', 'FL_L_ELBOW'),
        ('Elbow to Elbow Shot Fake → Reshape → Shot', 'FL_R_ELBOW'),
        ('Elbow to Elbow Shot Fake → Reshape → Shot', 'REGULAR'),
        ('Elbow to Elbow Shot Fake → Reshape → Shot', 'RESHOOT'),
        ('Elbow to Elbow Shot Fake → Reshape → Shot', 'SHOT_FAKE'),
        ('Elbow-to-Elbow Alternating Shots', '15FT'),
        ('Elbow-to-Elbow Alternating Shots', 'DEPTH_SHOOTING'),
        ('Elbow-to-Elbow Alternating Shots', 'FL_L_ELBOW'),
        ('Elbow-to-Elbow Alternating Shots', 'FL_R_ELBOW'),
        ('Elbow-to-Elbow Alternating Shots', 'REGULAR'),
        ('Free Throw Routine', 'FREE_THROW_ROUTINE'),
        ('High Rip Moves', '15FT'),
        ('High Rip Moves', 'FL_TOP_OF_FT'),
        ('High Rip Moves', 'HIGH_RIP'),
        ('High Rip Moves', 'REGULAR'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', '15FT'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'BEHIND_THE_BACK'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'FL_TOP_OF_FT'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'FRONT_CROSS'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'JAB'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'PULL_UP_R'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'REGULAR'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up', 'SLIDE_DRIBBLE_R'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', '15FT'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'BEHIND_THE_BACK'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'FL_TOP_OF_FT'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'FRONT_CROSS'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'JAB'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'PULL_UP_L'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'REGULAR'),
        ('Jab → Behind-Back → Crossover → Slide Pull-Up (Other Side)', 'SLIDE_DRIBBLE_L'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', '3PT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'BETWEEN_THE_LEGS'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'FL_R_ELBOW'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'FL_TOP_OF_KEY_3PT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'JAB'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'PUSH_OUT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'REGULAR'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3', 'RUN_OUT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', '3PT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'BETWEEN_THE_LEGS'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'FL_L_ELBOW'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'FL_TOP_OF_KEY_3PT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'JAB'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'PUSH_OUT'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'REGULAR'),
        ('Jab → Through-Legs → Push-Out → Run-Out 3 (Other Side)', 'RUN_OUT'),
        ('Left Block → Dribble to Elbow → Inside Pivot Shoot', '15FT'),
        ('Left Block → Dribble to Elbow → Inside Pivot Shoot', 'FL_L_BLOCK'),
        ('Left Block → Dribble to Elbow → Inside Pivot Shoot', 'FL_L_ELBOW'),
        ('Left Block → Dribble to Elbow → Inside Pivot Shoot', 'INSIDE_PIVOT'),
        ('Left Block → Dribble to Elbow → Inside Pivot Shoot', 'REGULAR'),
        ('Left Corner → Wing Sprint → Curl/Retreat Series', 'CURL_CUT'),
        ('Left Corner → Wing Sprint → Curl/Retreat Series', 'REGULAR'),
        ('Left Corner → Wing Sprint → Curl/Retreat Series', 'RETREAT_DRIBBLE'),
        ('Left Corner → Wing Sprint → Curl/Retreat Series', 'SL_L_CORNER'),
        ('Left Corner → Wing Sprint → Curl/Retreat Series', 'TRANSITION'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', '15FT'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', '1_DRIBBLE'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'CHAIR'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'CURL_CUT'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'FL_L_ELBOW'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'PULL_UP_L'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'REGULAR'),
        ('Left Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'RIP'),
        ('Left Elbow → Dribble To Opposite Elbow → Inside Pivot', '15FT'),
        ('Left Elbow → Dribble To Opposite Elbow → Inside Pivot', 'FL_L_ELBOW'),
        ('Left Elbow → Dribble To Opposite Elbow → Inside Pivot', 'FL_R_ELBOW'),
        ('Left Elbow → Dribble To Opposite Elbow → Inside Pivot', 'INSIDE_PIVOT'),
        ('Left Elbow → Dribble To Opposite Elbow → Inside Pivot', 'REGULAR'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', '15FT'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'COMBO_MOVE'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'FL_L_ELBOW'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'FL_R_ELBOW'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'REGULAR'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'STEP_BACK_R'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', '15FT'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'COMBO_MOVE'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'FL_L_ELBOW'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'FL_R_ELBOW'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'FRONT_CROSS'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'HESITATE'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'REGULAR'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'STEP_BACK_R'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', '15FT'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'COMBO_MOVE'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'FL_L_ELBOW'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'FL_R_ELBOW'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'REGULAR'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'RESHOOT'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'SHOT_FAKE'),
        ('Left Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Pump Fake Reshape Shot', 'STEP_BACK_R'),
        ('Left Wing → Corner Sprint (3-Move Sequence)', 'COMBO_MOVE'),
        ('Left Wing → Corner Sprint (3-Move Sequence)', 'FL_CORNER_3_L'),
        ('Left Wing → Corner Sprint (3-Move Sequence)', 'REGULAR'),
        ('Left Wing → Corner Sprint (3-Move Sequence)', 'SL_L_WING'),
        ('Left Wing → Corner Sprint (3-Move Sequence)', 'TRANSITION'),
        ('Low Block → Behind-Back → Pull-Up (3-Level)', '3PT'),
        ('Low Block → Behind-Back → Pull-Up (3-Level)', 'BEHIND_THE_BACK'),
        ('Low Block → Behind-Back → Pull-Up (3-Level)', 'FL_R_BLOCK'),
        ('Low Block → Behind-Back → Pull-Up (3-Level)', 'FL_TOP_OF_KEY_3PT'),
        ('Low Block → Behind-Back → Pull-Up (3-Level)', 'PULL_UP_R'),
        ('Low Block → Behind-Back → Pull-Up (3-Level)', 'REGULAR'),
        ('Low Block → Behind-Back → Pull-Up (3-Level) (Other Side)', '3PT'),
        ('Low Block → Behind-Back → Pull-Up (3-Level) (Other Side)', 'BEHIND_THE_BACK'),
        ('Low Block → Behind-Back → Pull-Up (3-Level) (Other Side)', 'FL_L_BLOCK'),
        ('Low Block → Behind-Back → Pull-Up (3-Level) (Other Side)', 'FL_TOP_OF_KEY_3PT'),
        ('Low Block → Behind-Back → Pull-Up (3-Level) (Other Side)', 'PULL_UP_L'),
        ('Low Block → Behind-Back → Pull-Up (3-Level) (Other Side)', 'REGULAR'),
        ('Low Rip Moves', '15FT'),
        ('Low Rip Moves', 'FL_TOP_OF_FT'),
        ('Low Rip Moves', 'LOW_RIP'),
        ('Low Rip Moves', 'REGULAR'),
        ('Outside-Leg Throwout Moves', '15FT'),
        ('Outside-Leg Throwout Moves', 'FL_TOP_OF_FT'),
        ('Outside-Leg Throwout Moves', 'OUTSIDE_LEG_THROWOUT'),
        ('Outside-Leg Throwout Moves', 'REGULAR'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', '15FT'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', 'FL_TOP_OF_FT'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', 'HESITATE'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', 'PICK_AND_ROLL'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', 'PULL_UP_R'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', 'REGULAR'),
        ('P&R Step‑Back → Hesitate → FT Pull-Up (Right)', 'STEP_BACK_R'),
        ('Pass Fake → Pound Dribble Series', '15FT'),
        ('Pass Fake → Pound Dribble Series', 'FL_TOP_OF_FT'),
        ('Pass Fake → Pound Dribble Series', 'PASS_FAKE'),
        ('Pass Fake → Pound Dribble Series', 'POUND_DRIBBLE'),
        ('Pass Fake → Pound Dribble Series', 'REGULAR'),
        ('Pick & Roll Left – Attack → Free-Throw Line Pull-Up', '15FT'),
        ('Pick & Roll Left – Attack → Free-Throw Line Pull-Up', 'FL_TOP_OF_FT'),
        ('Pick & Roll Left – Attack → Free-Throw Line Pull-Up', 'PICK_AND_ROLL'),
        ('Pick & Roll Left – Attack → Free-Throw Line Pull-Up', 'PULL_UP_L'),
        ('Pick & Roll Left – Attack → Free-Throw Line Pull-Up', 'REGULAR'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', '15FT'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', '3PT'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'FL_TOP_OF_FT'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'FL_TOP_OF_KEY_3PT'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'HESITATE'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'PICK_AND_ROLL'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'PULL_UP_L'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'REGULAR'),
        ('Pick & Roll Left – Step-Back → Hesitate/Show → Left Pull-Up', 'STEP_BACK_L'),
        ('Pick & Roll Right – Attack → Free-Throw Line Pull-Up', '15FT'),
        ('Pick & Roll Right – Attack → Free-Throw Line Pull-Up', 'FL_TOP_OF_FT'),
        ('Pick & Roll Right – Attack → Free-Throw Line Pull-Up', 'PICK_AND_ROLL'),
        ('Pick & Roll Right – Attack → Free-Throw Line Pull-Up', 'PULL_UP_R'),
        ('Pick & Roll Right – Attack → Free-Throw Line Pull-Up', 'REGULAR'),
        ('Pick & Roll Right – Defender Over Screen → Step-Back 3', '15FT'),
        ('Pick & Roll Right – Defender Over Screen → Step-Back 3', 'FL_TOP_OF_KEY_3PT'),
        ('Pick & Roll Right – Defender Over Screen → Step-Back 3', 'HOLD_OFF_OVER'),
        ('Pick & Roll Right – Defender Over Screen → Step-Back 3', 'PICK_AND_ROLL'),
        ('Pick & Roll Right – Defender Over Screen → Step-Back 3', 'REGULAR'),
        ('Pick & Roll Right – Defender Over Screen → Step-Back 3', 'STEP_BACK_R'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', '15FT'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', '3PT'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'BETWEEN_THE_LEGS'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'COMBO_MOVE'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'FL_TOP_OF_FT'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'FL_TOP_OF_KEY_3PT'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'HESITATE'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'PICK_AND_ROLL'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'PULL_UP_L'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'PULL_UP_R'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'REGULAR'),
        ('Pick & Roll Right – Step-Back → Hesitate → Between Legs → Right Pull-Up', 'STEP_BACK_R'),
        ('Pivot Move – Cross-Step', '15FT'),
        ('Pivot Move – Cross-Step', 'CROSS_STEP'),
        ('Pivot Move – Cross-Step', 'FL_TOP_OF_FT'),
        ('Pivot Move – Cross-Step', 'INSIDE_PIVOT'),
        ('Pivot Move – Cross-Step', 'REGULAR'),
        ('Pivot Move – Slip Dribble', '15FT'),
        ('Pivot Move – Slip Dribble', 'FL_TOP_OF_FT'),
        ('Pivot Move – Slip Dribble', 'INSIDE_PIVOT'),
        ('Pivot Move – Slip Dribble', 'REGULAR'),
        ('Pivot Move – Slip Dribble', 'SLIP_DRIBBLE'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', '3PT'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', 'FL_R_ELBOW'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', 'FL_TOP_OF_KEY_3PT'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', 'JAB'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', 'POUND_DRIBBLE'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', 'REGULAR'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3', 'SQUARE_UP'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', '3PT'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', 'FL_L_ELBOW'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', 'FL_TOP_OF_KEY_3PT'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', 'JAB'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', 'POUND_DRIBBLE'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', 'REGULAR'),
        ('Pound → 3/4 Pivot → Jab → Square-Up 3 (Other Side)', 'SQUARE_UP'),
        ('Right Block → Dribble to Elbow → Inside Pivot Shoot', '15FT'),
        ('Right Block → Dribble to Elbow → Inside Pivot Shoot', 'FL_R_BLOCK'),
        ('Right Block → Dribble to Elbow → Inside Pivot Shoot', 'FL_R_ELBOW'),
        ('Right Block → Dribble to Elbow → Inside Pivot Shoot', 'INSIDE_PIVOT'),
        ('Right Block → Dribble to Elbow → Inside Pivot Shoot', 'REGULAR'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', '15FT'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', '1_DRIBBLE'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'CHAIR'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'CURL_CUT'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'FL_R_ELBOW'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'PULL_UP_R'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'REGULAR'),
        ('Right Elbow Chair Curl → Rip Right → One-Dribble Pull-Up', 'RIP'),
        ('Right Elbow → Dribble To Opposite Elbow → Inside Pivot', '15FT'),
        ('Right Elbow → Dribble To Opposite Elbow → Inside Pivot', 'FL_L_ELBOW'),
        ('Right Elbow → Dribble To Opposite Elbow → Inside Pivot', 'FL_R_ELBOW'),
        ('Right Elbow → Dribble To Opposite Elbow → Inside Pivot', 'INSIDE_PIVOT'),
        ('Right Elbow → Dribble To Opposite Elbow → Inside Pivot', 'REGULAR'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', '15FT'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'COMBO_MOVE'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'FL_L_ELBOW'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'FL_R_ELBOW'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'REGULAR'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back', 'STEP_BACK_L'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', '15FT'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'COMBO_MOVE'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'FL_L_ELBOW'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'FL_R_ELBOW'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'FRONT_CROSS'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'HESITATE'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'REGULAR'),
        ('Right Elbow → Freestyle Dribble → Attack Opposite Elbow → Inside Foot Step Back → Hesitation → Crossover Middle', 'STEP_BACK_L'),
        ('Right Wing → Corner Sprint (3-Move Sequence)', 'COMBO_MOVE'),
        ('Right Wing → Corner Sprint (3-Move Sequence)', 'FL_CORNER_3_R'),
        ('Right Wing → Corner Sprint (3-Move Sequence)', 'REGULAR'),
        ('Right Wing → Corner Sprint (3-Move Sequence)', 'SL_R_WING'),
        ('Right Wing → Corner Sprint (3-Move Sequence)', 'TRANSITION'),
        ('Rollout Move', '15FT'),
        ('Rollout Move', 'FL_TOP_OF_FT'),
        ('Rollout Move', 'REGULAR'),
        ('Rollout Move', 'ROLLOUT'),
        ('Stop → Behind-Back → Crossover → Step-Back', '15FT'),
        ('Stop → Behind-Back → Crossover → Step-Back', 'BEHIND_THE_BACK'),
        ('Stop → Behind-Back → Crossover → Step-Back', 'COMBO_MOVE'),
        ('Stop → Behind-Back → Crossover → Step-Back', 'FL_TOP_OF_FT'),
        ('Stop → Behind-Back → Crossover → Step-Back', 'FRONT_CROSS'),
        ('Stop → Behind-Back → Crossover → Step-Back', 'REGULAR'),
        ('Stop → Behind-Back → Crossover → Step-Back', 'STEP_BACK_R'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', '15FT'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', 'BEHIND_THE_BACK'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', 'COMBO_MOVE'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', 'FL_TOP_OF_FT'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', 'FRONT_CROSS'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', 'REGULAR'),
        ('Stop → Behind-Back → Crossover → Step-Back (Other Side)', 'STEP_BACK_L'),
        ('Straight Cut Block to Wing → 3-Point Shot', '3PT'),
        ('Straight Cut Block to Wing → 3-Point Shot', 'FL_3PT_WING_R'),
        ('Straight Cut Block to Wing → 3-Point Shot', 'FL_R_BLOCK'),
        ('Straight Cut Block to Wing → 3-Point Shot', 'REGULAR'),
        ('Straight Cut Block to Wing → 3-Point Shot', 'RELOCATE'),
        ('Three Spots Shooting (Left Side)', 'DEPTH_SHOOTING'),
        ('Three Spots Shooting (Left Side)', 'FL_L_ELBOW'),
        ('Three Spots Shooting (Left Side)', 'REGULAR'),
        ('Three Spots Shooting (Right Side)', 'DEPTH_SHOOTING'),
        ('Three Spots Shooting (Right Side)', 'FL_R_ELBOW'),
        ('Three Spots Shooting (Right Side)', 'REGULAR'),
        ('Top of Key Ball Screen – Left Hand', '15FT'),
        ('Top of Key Ball Screen – Left Hand', '3PT'),
        ('Top of Key Ball Screen – Left Hand', 'FLAT_BALL_SCREEN'),
        ('Top of Key Ball Screen – Left Hand', 'FL_TOP_OF_FT'),
        ('Top of Key Ball Screen – Left Hand', 'FL_TOP_OF_KEY_3PT'),
        ('Top of Key Ball Screen – Left Hand', 'FRONT_CROSS'),
        ('Top of Key Ball Screen – Left Hand', 'PULL_UP_L'),
        ('Top of Key Ball Screen – Left Hand', 'REGULAR'),
        ('Top of Key Ball Screen – Left Hand', 'SL_TOK'),
        ('Top of Key Ball Screen – Left Hand Split', '3PT'),
        ('Top of Key Ball Screen – Left Hand Split', 'FLAT_BALL_SCREEN'),
        ('Top of Key Ball Screen – Left Hand Split', 'FL_TOP_OF_KEY_3PT'),
        ('Top of Key Ball Screen – Left Hand Split', 'PULL_UP_L'),
        ('Top of Key Ball Screen – Left Hand Split', 'REGULAR'),
        ('Top of Key Ball Screen – Left Hand Split', 'SL_TOK'),
        ('Top of Key Ball Screen – Left Hand Split', 'SPLIT'),
        ('Top of Key Ball Screen – Right Hand', '15FT'),
        ('Top of Key Ball Screen – Right Hand', '3PT'),
        ('Top of Key Ball Screen – Right Hand', 'FLAT_BALL_SCREEN'),
        ('Top of Key Ball Screen – Right Hand', 'FL_TOP_OF_FT'),
        ('Top of Key Ball Screen – Right Hand', 'FL_TOP_OF_KEY_3PT'),
        ('Top of Key Ball Screen – Right Hand', 'FRONT_CROSS'),
        ('Top of Key Ball Screen – Right Hand', 'PULL_UP_R'),
        ('Top of Key Ball Screen – Right Hand', 'REGULAR'),
        ('Top of Key Ball Screen – Right Hand', 'SL_TOK'),
        ('Top of Key Ball Screen – Right Hand Split', '3PT'),
        ('Top of Key Ball Screen – Right Hand Split', 'FLAT_BALL_SCREEN'),
        ('Top of Key Ball Screen – Right Hand Split', 'FL_TOP_OF_KEY_3PT'),
        ('Top of Key Ball Screen – Right Hand Split', 'PULL_UP_R'),
        ('Top of Key Ball Screen – Right Hand Split', 'REGULAR'),
        ('Top of Key Ball Screen – Right Hand Split', 'SL_TOK'),
        ('Top of Key Ball Screen – Right Hand Split', 'SPLIT'),
        ('Top of Key Sprint Series (Left-Hand Variations)', 'COMBO_MOVE'),
        ('Top of Key Sprint Series (Left-Hand Variations)', 'FL_TOP_OF_KEY_3PT'),
        ('Top of Key Sprint Series (Left-Hand Variations)', 'PULL_UP_L'),
        ('Top of Key Sprint Series (Left-Hand Variations)', 'REGULAR'),
        ('Top of Key Sprint Series (Left-Hand Variations)', 'SL_TOK'),
        ('Top of Key Sprint Series (Left-Hand Variations)', 'TRANSITION'),
        ('Top of Key Sprint Series (Right-Hand Variations)', 'COMBO_MOVE'),
        ('Top of Key Sprint Series (Right-Hand Variations)', 'FL_TOP_OF_KEY_3PT'),
        ('Top of Key Sprint Series (Right-Hand Variations)', 'PULL_UP_R'),
        ('Top of Key Sprint Series (Right-Hand Variations)', 'REGULAR'),
        ('Top of Key Sprint Series (Right-Hand Variations)', 'SL_TOK'),
        ('Top of Key Sprint Series (Right-Hand Variations)', 'TRANSITION'),
        ('Top → Corner Sprint → 3', '3PT'),
        ('Top → Corner Sprint → 3', 'FL_3PT_WING_R'),
        ('Top → Corner Sprint → 3', 'REGULAR'),
        ('Top → Corner Sprint → 3', 'SL_TOK'),
        ('Top → Corner Sprint → 3', 'TRANSITION'),
        ('Top → Corner Sprint → 3 (Other Side)', '3PT'),
        ('Top → Corner Sprint → 3 (Other Side)', 'FL_3PT_WING_L'),
        ('Top → Corner Sprint → 3 (Other Side)', 'REGULAR'),
        ('Top → Corner Sprint → 3 (Other Side)', 'SL_TOK'),
        ('Top → Corner Sprint → 3 (Other Side)', 'TRANSITION'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', '15FT'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', 'CATCH_AND_SHOOT'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', 'FL_TOP_OF_FT'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', 'PULL_UP_R'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', 'REGULAR'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', 'SHOT_FAKE'),
        ('Transition Sprint → Catch & Shoot / Shot Fake → Pull-Up (Right Side)', 'TRANSITION'),
        ('Wheel-Up Cut → Wing 3-Point Shot', '1_DRIBBLE'),
        ('Wheel-Up Cut → Wing 3-Point Shot', '2_DRIBBLE'),
        ('Wheel-Up Cut → Wing 3-Point Shot', '3PT'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'CURL_CUT'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'DEPTH_SHOOTING'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'FL_3PT_WING_L'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'FL_3PT_WING_R'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'PULL_UP_L'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'PULL_UP_R'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'REGULAR'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'SHOT_FAKE'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'STEP_BACK_L'),
        ('Wheel-Up Cut → Wing 3-Point Shot', 'STEP_BACK_R'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', '3PT'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', 'FLAT_BALL_SCREEN'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', 'FL_3PT_WING_L'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', 'PULL_UP_L'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', 'REGULAR'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', 'RESCREEN'),
        ('Wing Ball Screen → Rescreen → Rescreen (Left Hand)', 'SL_L_WING'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', '3PT'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', 'FLAT_BALL_SCREEN'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', 'FL_3PT_WING_R'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', 'PULL_UP_R'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', 'REGULAR'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', 'RESCREEN'),
        ('Wing Ball Screen → Rescreen → Rescreen (Right Hand)', 'SL_R_WING'),
        ('Wing to Corner 3 Pt Series Left Wing', '3PT'),
        ('Wing to Corner 3 Pt Series Left Wing', 'COMBO_MOVE'),
        ('Wing to Corner 3 Pt Series Left Wing', 'FADE_CUT'),
        ('Wing to Corner 3 Pt Series Left Wing', 'FL_CORNER_3_L'),
        ('Wing to Corner 3 Pt Series Left Wing', 'REGULAR'),
        ('Wing to Corner 3 Pt Series Left Wing', 'SL_L_WING'),
        ('Wing to Corner 3 Pt Series Right Wing', '3PT'),
        ('Wing to Corner 3 Pt Series Right Wing', 'COMBO_MOVE'),
        ('Wing to Corner 3 Pt Series Right Wing', 'FADE_CUT'),
        ('Wing to Corner 3 Pt Series Right Wing', 'FL_CORNER_3_R'),
        ('Wing to Corner 3 Pt Series Right Wing', 'REGULAR'),
        ('Wing to Corner 3 Pt Series Right Wing', 'SL_R_WING'),
        ('Wing → Corner Slide → Catch & Shoot', '3PT'),
        ('Wing → Corner Slide → Catch & Shoot', 'CATCH_AND_SHOOT'),
        ('Wing → Corner Slide → Catch & Shoot', 'FADE_CUT'),
        ('Wing → Corner Slide → Catch & Shoot', 'FL_3PT_WING_L'),
        ('Wing → Corner Slide → Catch & Shoot', 'FL_CORNER_3_R'),
        ('Wing → Corner Slide → Catch & Shoot', 'REGULAR'),
        ('Wing → Corner Slide → Catch & Shoot', 'RELOCATE'),
        ('Wing → Corner Slide → Catch & Shoot', 'SL_R_CORNER'),
        ('Wing → Corner Slide → Catch & Shoot', 'SL_R_WING'),
        ('Wing → Corner Slide → Catch & Shoot (Other Side)', '3PT'),
        ('Wing → Corner Slide → Catch & Shoot (Other Side)', 'CATCH_AND_SHOOT'),
        ('Wing → Corner Slide → Catch & Shoot (Other Side)', 'FADE_CUT'),
        ('Wing → Corner Slide → Catch & Shoot (Other Side)', 'FL_CORNER_3_L'),
        ('Wing → Corner Slide → Catch & Shoot (Other Side)', 'REGULAR'),
        ('Wing → Corner Slide → Catch & Shoot (Other Side)', 'SL_L_WING'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3', '3PT'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3', 'FL_R_ELBOW'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3', 'FL_TOP_OF_KEY_3PT'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3', 'PULL_UP_R'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3', 'REGULAR'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3', 'WRAP_DRIBBLE'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3 (Other Side)', '3PT'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3 (Other Side)', 'FL_L_ELBOW'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3 (Other Side)', 'FL_TOP_OF_KEY_3PT'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3 (Other Side)', 'PULL_UP_L'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3 (Other Side)', 'REGULAR'),
        ('Wrap Dribble → Attack Elbow → Pull-Up 3 (Other Side)', 'WRAP_DRIBBLE')
)
INSERT INTO t_drill_item_tag (drill_item_id, tag_id)
SELECT di.id, t.id
FROM drill_tag_pairs p
JOIN t_drill_item di ON di.name = p.db_name
JOIN tags t ON t.code = p.tag_code
ON CONFLICT (drill_item_id, tag_id) DO NOTHING;
