-- DROP TABLE IF EXISTS t_drill_attempt CASCADE;

-- DROP TABLE IF EXISTS t_drill CASCADE;

-- DROP TABLE IF EXISTS t_drill_item CASCADE;

-- DROP TABLE IF EXISTS t_drill_level CASCADE;

-- DROP TABLE IF EXISTS t_drill_group CASCADE;

-- -- Notes: This models a series of drills at the highest group
-- -- Basketball: Elementary, Middle School, High School
-- CREATE TABLE t_drill_group (
--     id                        UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--     team_id                   UUID NOT NULL REFERENCES t_team(id) DEFERRABLE INITIALLY DEFERRED,
--     name                      VARCHAR(2048),
--     description               TEXT,
--     drill_group_order         INTEGER NOT NULL DEFAULT 1,
--     drill_group_type_code     VARCHAR(40) DEFAULT 'DRILL' NOT NULL, -- DRILL, CHECKPOINT
--     creation_date             BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     modification_date         BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     created_by_id             UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     modified_by_id            UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     version                   INTEGER NOT NULL DEFAULT 0
-- );

-- -- Notes: The exercises that are contained within a drill
-- -- Drill 1: 5 Free Throws in 30 Seconds
-- -- Drill 2: 20 Layups
-- -- Drill 3: 10 3-pointers
-- -- Drill 4: 4 Hook Shots
-- CREATE TABLE t_drill_item (
--     id                        UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--     drill_group_id            UUID NOT NULL REFERENCES t_drill_group(id) DEFERRABLE INITIALLY DEFERRED,
--     name                      VARCHAR(2048),
--     description               TEXT,
--     media_id                  UUID REFERENCES t_media(id) DEFERRABLE INITIALLY DEFERRED,
--     level_index               INTEGER NOT NULL DEFAULT 1,
--     drill_item_order          INTEGER NOT NULL DEFAULT 1,
--     passing_score             INTEGER NOT NULL DEFAULT 3, -- the minimum number of HITS
--     visibility_code           VARCHAR(40) DEFAULT 'PRIVATE' NOT NULL, -- PUBLIC,  PRIVATE
--     allow_retry_code          VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL,
--     retry_max                 INTEGER NOT NULL DEFAULT 3,
--     time_limit_ms             BIGINT NOT NULL DEFAULT 300000,
--     creation_date             BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     modification_date         BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     created_by_id             UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     modified_by_id            UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     version                   INTEGER NOT NULL DEFAULT 0
-- );

-- -- Note: The instance of a user starting a drill template. Should be created when they start
-- CREATE TABLE t_drill (
--     id                        UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--     drill_item_id             UUID NOT NULL REFERENCES t_drill_item(id) DEFERRABLE INITIALLY DEFERRED,
--     user_id                   UUID NOT NULL REFERENCES t_user(id) DEFERRABLE INITIALLY DEFERRED,
--     media_id                  UUID REFERENCES t_media(id) DEFERRABLE INITIALLY DEFERRED,
--     drill_status              VARCHAR(40) DEFAULT 'OPEN' NOT NULL, -- PASSED, SKIPPED, FAILED
--     creation_date             BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     modification_date         BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     created_by_id             UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     modified_by_id            UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     version                   INTEGER NOT NULL DEFAULT 0
-- );

-- -- Note: Each item in the drill
-- CREATE TABLE t_drill_attempt (
--     id                        UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--     drill_id                  UUID NOT NULL REFERENCES t_drill(id) DEFERRABLE INITIALLY DEFERRED,
--     media_id                  UUID NOT NULL REFERENCES t_media(id) DEFERRABLE INITIALLY DEFERRED,
--     start_time                BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     end_time                  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     elapsed_time              BIGINT NOT NULL DEFAULT 0,
--     score                     INTEGER NOT NULL DEFAULT 0, -- the minimum number of HITS
--     retries                   INTEGER NOT NULL DEFAULT 0,
--     drill_attempt_status      VARCHAR(40) DEFAULT 'OPEN' NOT NULL, -- PASSED, SKIPPED, FAILED
--     creation_date             BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     modification_date         BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     created_by_id             UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     modified_by_id            UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     version                   INTEGER NOT NULL DEFAULT 0
-- );
