-- CREATE TABLE t_like (
--     id                 UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--     user_id            UUID NOT NULL REFERENCES t_user(id) DEFERRABLE INITIALLY DEFERRED,
--     like_type          VARCHAR(40), -- LIKE, LOVE, SMILEY
--     status_code        VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, ARCHIVED, DELETED
--     creation_date      BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     modification_date  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     created_by_id      UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     modified_by_id     UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     version            INTEGER NOT NULL DEFAULT 0
-- );

-- CREATE TABLE t_comment (
--     id                 UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--     user_id            UUID NOT NULL REFERENCES t_user(id) DEFERRABLE INITIALLY DEFERRED,
--     comment_type       VARCHAR(40), -- POST, REPLY
--     comment_value      TEXT,
--     status_code        VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, ARCHIVED, DELETED
--     creation_date      BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     modification_date  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000),
--     created_by_id      UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     modified_by_id     UUID NOT NULL DEFAULT 'd79ab826-65de-4fda-8b5f-779dacfe00fe'::UUID,
--     version            INTEGER NOT NULL DEFAULT 0
-- );

-- CREATE TABLE t_challenge_entry_like_xref (
--     challenge_entry_id UUID NOT NULL REFERENCES t_challenge_entry(id) DEFERRABLE INITIALLY DEFERRED,
--     user_id            UUID NOT NULL REFERENCES t_user(id) DEFERRABLE INITIALLY DEFERRED,
--     like_id            UUID NOT NULL REFERENCES t_like(id) DEFERRABLE INITIALLY DEFERRED,
--     PRIMARY KEY (challenge_entry_id, user_id) -- enforce only one like per challenge entry per user
-- );

-- CREATE TABLE t_challenge_entry_comment_xref (
--     challenge_entry_id UUID NOT NULL REFERENCES t_challenge_entry(id) DEFERRABLE INITIALLY DEFERRED,
--     user_id            UUID NOT NULL REFERENCES t_user(id) DEFERRABLE INITIALLY DEFERRED,
--     comment_id         UUID NOT NULL REFERENCES t_comment(id) DEFERRABLE INITIALLY DEFERRED
-- );
