-- --
-- -- Make sure that every current active user is in the Every Shot Counts
-- -- organization and on the Every Shot Counts team

-- WITH cte_data AS (
--   SELECT u.id AS user_id
--     FROM t_user u
--   WHERE u.status_code = 'ACTIVE'
--   ORDER BY u.id ASC
-- ), d1 AS (
--   DELETE FROM t_organization_user_xref
--    WHERE user_id IN (
--      SELECT user_id FROM cte_data
--    )
-- ) INSERT INTO t_organization_user_xref (
--   organization_id,
--   team_id,
--   user_id,
--   verification_code
-- ) SELECT 'a575815a-cbff-404e-a808-f99ecaac2ab2' -- every shot counts
--        , 'fc793899-489c-4bd9-bf80-616e1318e714' -- every shot counts
--        , user_id
--        , 'VERIFIED'
--     FROM cte_data;
