package com.lektralabs.thrones.pallbearer.common;

public interface AddressConstants {

    String PRIMARY_RESIDENCE = "PRIMARY_RESIDENCE";
    String SECONDARY_RESIDENCE = "SECONDARY_RESIDENCE";
    String PRIMARY_VACATION = "PRIMARY_VACATION";
    String SECONDARY_VACATION = "SECONDARY_VACATION";
    String PRIMARY_BUSINESS = "PRIMARY_BUSINESS";
    String SECONDARY_BUSINESS = "SECONDARY_BUSINESS";

}
