<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <parent>
        <groupId>com.lektralabs.thrones.pallbearer</groupId>
        <artifactId>pallbearer-reactor-project</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pallbearer-reactor/pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <name>pallbearer-api-project</name>
    <groupId>com.lektralabs.thrones.pallbearer</groupId>
    <artifactId>pallbearer-api-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <url>https://www.lektralabs.com</url>

    <dependencies>
        <dependency>
            <groupId>com.lektralabs.thrones.pallbearer</groupId>
            <artifactId>pallbearer-core-project</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.lektralabs.thrones.pallbearer</groupId>
            <artifactId>leagueapps-project</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>

        <!-- JUNIT TESTING (versions match pallbearer-core) -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.0-RC1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.0-RC1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.11.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.11.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
