name: CI

on:
  push:
    branches:
      - 'feat/**'
      - '!feat/development'
  pull_request:
    branches:
      - feat/development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn clean install -DskipTests=true

      - name: Test
        run: mvn test --fail-at-end
